// src/routes/Footer.svelte
<script lang="ts">
	import { Icon } from '@steeze-ui/svelte-icon';
	import { BrandDiscord, BrandTelegram, Mail } from '@steeze-ui/tabler-icons';
</script>

<footer class="w-full py-10">
	<div class="flex flex-col items-center justify-center gap-5">
		<p>
			©{new Date().getFullYear()} Tamer Hayek
		</p>
		<div class="flex gap-10 pb-5">
			<a href={'mailto:dev@tamerhayek.com'}>
				<Icon src={Mail} size="30px" class="transition-all hover:scale-110" />
				<span class="sr-only">Mail</span>
			</a>
			<a target="_blank" href={'https://tamerhayek.com/telegram'}>
				<Icon src={BrandTelegram} size="30px" class="transition-all hover:scale-110" />
				<span class="sr-only">Telegram</span>
			</a>
			<a target="_blank" href={'https://tamerhayek.com/discord'}>
				<Icon src={BrandDiscord} size="30px" class="transition-all hover:scale-110" />
				<span class="sr-only">Discord</span>
			</a>
		</div>
	</div>
</footer>

// components/Layout/Footer/Footer.tsx
import Link from "next/link";
import { MdEmail } from "react-icons/md";
import { SiTelegram, SiDiscord } from "react-icons/si";

const Footer = () => {
	return (
		<section id="footer" className="my-10 py-10">
			<div className="flex flex-col items-center justify-center gap-5 min-h-[100px]">
				<h3 className="text-gray-400 text-md 2xl:text-xl">
					©2023 Tamer Hayek. All rights reserved.
				</h3>
				<div className="flex gap-10 pb-5">
					<Link href={"mailto:dev@tamerhayek.com"}>
						<MdEmail className="w-7 h-7 xl:w-10 xl:h-10 hover:scale-110 transition-all" />
					</Link>
					<Link href={"https://t.me/tamibyte"}>
						<SiTelegram className="w-7 h-7 xl:w-10 xl:h-10 hover:scale-110 transition-all" />
					</Link>
					<Link href={"https://discord.com/channels/tamibyte"}>
						<SiDiscord className="w-7 h-7 xl:w-10 xl:h-10 hover:scale-110 transition-all" />
					</Link>
				</div>
			</div>
		</section>
	);
};

export default Footer;
