// src/lib/components/Navbar.svelte
<script lang="ts">
	import { Icon } from '@steeze-ui/svelte-icon';
	import { BrandGithub, BrandInstagram, BrandLinkedin } from '@steeze-ui/tabler-icons';
</script>

<nav id="navbar" class="bg-base-200 fixed top-0 z-50 flex w-full items-center justify-center">
	<div class="flex w-full max-w-6xl items-center justify-between px-5 py-5">
		<div
			class="h-12 w-12 shrink-0 overflow-hidden rounded-full bg-gradient-to-b from-teal-200 to-teal-700 object-contain"
		>
			<a href="/">
				<img src="/avatar.png" alt="Tamer's avatar" fetchPriority="high" />
			</a>
		</div>
		<div class="flex shrink-0 items-center justify-center gap-3 lg:justify-start lg:gap-5">
			<a
				class="cursor-pointer"
				target="_blank"
				rel="noreferrer, noopener"
				href="https://github.com/tamerhayek"
			>
				<Icon src={BrandGithub} size="40px" class="transition-colors  hover:text-purple-700" />
				<span class="sr-only">Github</span>
			</a>
			<a
				class="cursor-pointer"
				target="_blank"
				rel="noreferrer, noopener"
				href="https://www.linkedin.com/in/tamerhayek/"
			>
				<Icon src={BrandLinkedin} size="40px" class="transition-colors  hover:text-blue-500" />
				<span class="sr-only">Linkedin</span>
			</a>
			<a
				class="cursor-pointer"
				target="_blank"
				rel="noreferrer, noopener"
				href="https://www.instagram.com/tamerhayek/"
			>
				<Icon src={BrandInstagram} size="40px" class="transition-colors  hover:text-pink-500" />
				<span class="sr-only">Instagram</span>
			</a>
		</div>
	</div>
</nav>

// components/Layout/Navbar/Navbar.tsx
import SocialIcons from "@/components/ui/SocialIcons";
import avatar from "@/public/avatar.png";
import Image from "next/image";
import Link from "next/link";

const Navbar = () => {
	return (
		<nav id="navbar" className="fixed w-full bg-background z-50 top-0">
			<div className="flex justify-between items-center px-5 py-5 lg:px-20 2xl:px-40">
				<div className="w-12 h-12 rounded-full bg-gradient-to-b from-teal-200 to-teal-700 overflow-hidden object-contain">
					<Link href={"/"}>
						<Image
							src={avatar}
							alt="Tamer's avatar"
							priority={true}
						/>
					</Link>
				</div>
				<SocialIcons />
			</div>
		</nav>
	);
};

export default Navbar;
